minio:
  displayName: minio
  identityOpenidClaimName: policy
  identityOpenidClientId: minio
  identityOpenidClientSecret: UpdD4pN6omB7JmjQU0piKjuPKU2fujbq
  identityOpenidConfigUrl:
  identityOpenidScopes: openid
  identityOpenidRedirectUriDynamic: on
  domain: uds.dev
  rootPassword:
  rootUser: minio



