
name: uds-minio
identityOpenidClientSecret: "replaceme"
identityOpenidConfigUrl:
domain: uds.dev
rootPassword:
rootUser: minio
# sso disabled until we can define the protocol mappers via sso secret
# or update the uds-core keycloak image
sso:
  enabled: false
copyPassword:
  enabled: false
  namespace: ""
  secretName: ""
  secretIDKey:
  secretPasswordKey:
custom: []
