minio:
  displayName: minio
  identityOpenidClaimName: policy
  identityOpenidClientId: minio
  identityOpenidClientSecret: "exampleClientSecret"
  identityOpenidConfigUrl:
  identityOpenidScopes: openid
  identityOpenidRedirectUriDynamic: on
  domain: uds.dev
  rootPassword:
  rootUser: minio

sso:
  enabled: false
copyPassword:
  enabled: false
  namespace: ""
  secretName: ""
  secretKey: ""

custom: []

