# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

tenant:
  image:
    repository: registry1.dso.mil/ironbank/opensource/minio/minio
    # renovate: datasource=docker depName=registry1.dso.mil/ironbank/opensource/minio/minio versioning=regex:^RELEASE\.(?<major>\d+)-(?<minor>\d+)-(?<patch>\d+)T(?<build>\d+)-(?<revision>\d+)-\d+Z$
    tag: RELEASE.2025-05-24T17-08-30Z
    pullPolicy: IfNotPresent
