# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

tenant:
  image:
    repository: registry1.dso.mil/ironbank/opensource/minio/minio
    tag: RELEASE.2024-06-04T19-20-08Z
    pullPolicy: IfNotPresent
