operator:
  image:
    repository: quay.io/minio/operator
    tag: v5.0.15
# Note Operator console is deprecated and removed on next major release (6.0.0)
console:
  image:
    repository: quay.io/minio/operator
    tag: v5.0.15