# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

tenant:
  image:
    repository: quay.io/minio/minio
    tag: RELEASE.2024-08-03T04-33-23Z
