# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{- range $app := .Values.apps }}
{{- if or (not (hasKey $app "policy")) (eq $app.policy "") }}
{{- $bucketNames := $app.bucketNames | default list }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-minio-policy
  namespace: minio
data:
  policy.json: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": [
            "s3:GetBucketLocation",
            "s3:ListBucket",
            "s3:ListBucketMultipartUploads"
          ],
          "Resource": [
            {{- range $index, $bucket := $bucketNames }}
            "arn:aws:s3:::{{ $bucket }}"{{ if lt (add $index 1) (len $bucketNames) }},{{ end }}
            {{- end }}
          ]
        },
        {
          "Effect": "Allow",
          "Action": [
            "s3:AbortMultipartUpload",
            "s3:DeleteObject",
            "s3:GetObject",
            "s3:ListMultipartUploadParts",
            "s3:PutObject"
          ],
          "Resource": [
            {{- range $index, $bucket := $bucketNames }}
            "arn:aws:s3:::{{ $bucket }}/*"{{ if lt (add $index 1) (len $bucketNames) }},{{ end }}
            {{- end }}
          ]
        }
      ]
    }
---
{{- else }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-minio-policy
  namespace: minio
data:
  policy.json: |
{{ tpl $app.policy $app | indent 4 }}
---
{{- end }}
{{- end }}
