apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: "minio-operator"
  namespace: {{ .Release.Namespace }}
spec:
  network:
    expose:       
      - service: console
        selector:
          app.kubernetes.io/instance: minio-operator-console
        host: minio-operator-console
        gateway: admin
        port: 9090
      - service: sts
        selector:
          app.kubernetes.io/name: operator
        host: minio-sts
        gateway: tenant
        port: 4223
    allow:
      # - direction: Ingress
      #   remoteNamespace: minio
      #   remoteSelector:
      #     v1.min.io/tenant: uds-minio-dev
      #   selector:
      #     app.kubernetes.io/name: operator
      #   port: 4221
      #   description: "ingress from tenant"
    # # TODO @zachariahmiller narrow down and add "custom" rules template
      - direction: Ingress
        remoteGenerated: Anywhere
      - direction: Egress
        remoteGenerated: Anywhere
      - direction: Ingress
        remoteGenerated: IntraNamespace
      - direction: Egress
        remoteGenerated: IntraNamespace
      - direction: Egress
        selector:
          app.kubernetes.io/name: operator 
        remoteGenerated: KubeAPI


      # Custom rules for unanticipated scenarios
      {{- range .Values.custom }}
      - direction: {{ .direction }}
        selector:
          {{ .selector | toYaml | nindent 10 }}
        {{- if not .remoteGenerated }}
        remoteNamespace: {{ .remoteNamespace }}
        remoteSelector:
          {{ .remoteSelector | toYaml | nindent 10 }}
        port: {{ .port }}
        {{- else }}
        remoteGenerated: {{ .remoteGenerated }}
        {{- end }}
        description: {{ .description }}
      {{- end }}