# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: "minio-operator"
  namespace: {{ .Release.Namespace }}
spec:
  network:
    allow:
      - direction: Egress
        remoteNamespace: minio
        remoteSelector:
          v1.min.io/tenant: {{ .Values.name }}
        selector:
          app.kubernetes.io/name: operator
        description: "Egress to tenant"
      - direction: Ingress
        remoteNamespace: minio
        remoteSelector:
          v1.min.io/tenant: {{ .Values.name }}
        selector:
          app.kubernetes.io/name: operator
        description: "Ingress from tenant"

      - direction: Egress
        selector:
          app.kubernetes.io/name: operator 
        remoteGenerated: KubeAPI
